### ISSUE TITLE
better handling of ElasticSearch 503 - queue full

### ISSUE THREAD

**Issue by mwotton** [ocharles/Elasticsearch#3]
I've hit this a few times using the individual indexing - if you hit an ES node hard enough, you fill up its whole queue (200 places, from memory), and it starts issuing 503s. These could be automatically retried by the library, perhaps? Or at the very least, issuing a less stern response than throwing error "server problem".

**Comment by mwotton** [comment]
digging into this a bit more. I have a test that provokes it now - just wondering whether it's the job of the library to manage the kind of exponential backoff that I currently do manually in my app. What do you think, @ocharles ?

**Comment by mwotton** [comment]
in general, we should not have "error" calls in the library - if an exception must be thrown it should be a specialised one.

**Comment by ocharles** [comment]
Closing in favor of [`bloodhound`](http://hackage.haskell.org/package/bloodhound). I am no longer working on this library (or doing anything with ElasticSearch), so it's unlikely to see the light of day.

**Comment by mwotton** [comment]
fair enough, i'm not using this or even bloodhound or elasticsearch any more, so I guess neither of us care :)
