### ISSUE TITLE
We should take a list of servers and retry the next one when one is down

### ISSUE THREAD

**Issue by mwotton** [ocharles/Elasticsearch#6]
inevitably in a big cluster shards will be down occasionally. We don't want to wait for them, so let's aim it at a different server when a request times out or gets rejected.

**Comment by ocharles** [comment]
Closing in favor of [`bloodhound`](http://hackage.haskell.org/package/bloodhound). I am no longer working on this library (or doing anything with ElasticSearch), so it's unlikely to see the light of day.
