### ISSUE TITLE
doesn't build with latest aeson

### ISSUE THREAD

**Issue by mwotton** [ocharles/Elasticsearch#8]
(this is @mwotton's code at fault, just don't want to forget about it)

src/Search/ElasticSearch.hs:293:26:
    No instance for (FromJSON Char8.ByteString)
      arising from a use of `.:'

upstream change in aeson - should be using Text here, because json is not defined over arbitrary bytestrings. https://github.com/bos/aeson/issues/126

**Comment by ocharles** [comment]
Closing in favor of [`bloodhound`](http://hackage.haskell.org/package/bloodhound). I am no longer working on this library (or doing anything with ElasticSearch), so it's unlikely to see the light of day.
